# Generated by Django 3.1.4 on 2020-12-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201203_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj_product',
            old_name='stuck',
            new_name='stock',
        ),
    ]
