# Generated by Django 3.1.3 on 2020-12-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201203_1406'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dj_product',
            table='Dj_Product',
        ),
    ]
