# Generated by Django 3.1.3 on 2020-12-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201204_0326'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dj_order',
            table='Dj_Order',
        ),
    ]
