# Generated by Django 3.1.4 on 2020-12-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201208_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj_order',
            name='status',
            field=models.CharField(choices=[('대기중', '대기중'), ('결재대기중', '결재대기'), ('결제완료', '결제완료'), ('환불', '환불')], default='대기중', max_length=32, verbose_name='상태'),
        ),
    ]
