# Generated by Django 3.1.3 on 2020-11-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='resistered_dttm',
            new_name='registered_dttm',
        ),
    ]
