# Generated by Django 3.1.3 on 2020-12-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj_user',
            name='level',
            field=models.CharField(choices=[('admin', 'admin')], max_length=8, null=True, verbose_name='등급'),
        ),
        migrations.AlterModelTable(
            name='dj_user',
            table='Dj_User',
        ),
    ]
