# Generated by Django 3.1.3 on 2020-12-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201204_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj_user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='비밀번호'),
        ),
    ]
